"""Build the `aikido_exl3_kernels` torch extension (Hopper sm_90 EXL3 kernels).

    source /scratch/aikido/env.sh
    cd /scratch/aikido/exl3/csrc && ./build.sh            # full: rows<=8/16/32/48/64 families, MUL1 + MCG
    cd /scratch/aikido/exl3/csrc && ./build.sh small      # rows<=16 families, MUL1 only (fast iteration)

Result: build/lib/aikido_exl3_kernels*.so  (PYTHONPATH=/scratch/aikido/exl3/csrc/build/lib)

Env: AIKIDO_MBS="0,1,2,3,4" row-block families (0 = rows<=8 transposed MMA, m = rows<=16m);
     AIKIDO_CODEBOOKS="1,2" (0 = 3INST, 1 = MCG, 2 = MUL1); AIKIDO_KBITS="3,4,6" (EXL3 bits per weight; 3 = byte-exact tile staging, K3).
     One generated .cu per (family, codebook, K). AIKIDO_WRAP_LOAD=0 restores the lane shuffle for the K=4 wrap bits
     (default 1: second shared-memory load, 0.4-1.0 us per launch faster on H200, same decoded bits).
"""
import os
from setuptools import setup
from torch.utils import cpp_extension

here = os.path.dirname(os.path.abspath(__file__))
mbs = [m.strip() for m in os.environ.get("AIKIDO_MBS", "0,1,2,3,4").split(",") if m.strip()]
cbs = [c.strip() for c in os.environ.get("AIKIDO_CODEBOOKS", "1,2").split(",") if c.strip()]
kbs = [b.strip() for b in os.environ.get("AIKIDO_KBITS", "3,4,6").split(",") if b.strip()]   # K3: default includes 3
gen = os.path.join(here, "build", "gen")
os.makedirs(gen, exist_ok=True)
sources = ["exl3_hopper.cu"]
variants = [(mb, cb, kb) for mb in mbs for cb in cbs for kb in kbs]
for mb, cb, kb in variants:
    path = os.path.join(gen, f"inst_mb{mb}_cb{cb}_k{kb}.cu")
    text = (f"#define AIKIDO_INST_MB {mb}\n#define AIKIDO_INST_CB {cb}\n#define AIKIDO_INST_KB {kb}\n"
            "#include \"exl3_hopper_inst.h\"\n")
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)
    sources.append(os.path.relpath(path, here))
fam = os.path.join(gen, "aikido_families.h")
fam_text = ("// generated by setup.py\n#pragma once\n#define AIKIDO_VARIANTS(X) "
            + " ".join(f"X({mb}, {cb}, {kb})" for mb, cb, kb in variants) + "\n")
if not os.path.exists(fam) or open(fam).read() != fam_text:
    open(fam, "w").write(fam_text)
# kernels are instantiated in their own translation units: their host stubs must have external linkage
nvcc = ["-lineinfo", "-O3", "--use_fast_math", "-std=c++17", "-static-global-template-stub=false",
        "-DAIKIDO_WRAP_LOAD=" + os.environ.get("AIKIDO_WRAP_LOAD", "1"),
        "-DAIKIDO_PROBES=" + os.environ.get("AIKIDO_PROBES", "0"),
        "-DAIKIDO_SLOT_REDUCE=" + os.environ.get("AIKIDO_SLOT_REDUCE", "1"),
        "-DAIKIDO_MOE_MINBLOCKS_M8=" + os.environ.get("AIKIDO_MOE_MINBLOCKS_M8", "2"),
        "-DAIKIDO_MCG_SELFADD=" + os.environ.get("AIKIDO_MCG_SELFADD", "1"),
        "-DAIKIDO_K3_IMAD_SHIFTS=" + os.environ.get("AIKIDO_K3_IMAD_SHIFTS", "0")]
if os.environ.get("AIKIDO_FORCE_OUT_FLAGS"):   # experiment only: every GEMM launch applies the output transform
    nvcc.append("-DAIKIDO_FORCE_OUT_FLAGS=" + os.environ["AIKIDO_FORCE_OUT_FLAGS"])

ext_modules = [
    cpp_extension.CUDAExtension(
        "aikido_exl3_kernels",
        sources,
        include_dirs=[here, os.path.join(here, "third_party", "marlin"), gen],
        extra_compile_args={"cxx": ["-O3"], "nvcc": nvcc},
    )
]

# ---- MoE front (begin): second extension `aikido_exl3_moe_kernels` = exl3_hopper_moe.cu + one generated unit per
# (moe block family, codebook), K = 4 only. AIKIDO_MOE=0 skips it, AIKIDO_MOE=only builds nothing else;
# AIKIDO_MOE_MBS="0,1,2,3,4" (0 = 8 rows per moe block, m = 16m rows), AIKIDO_MOE_CODEBOOKS defaults to AIKIDO_CODEBOOKS.
moe_mode = os.environ.get("AIKIDO_MOE", "1")
if moe_mode != "0":
    moe_mbs = [m.strip() for m in os.environ.get("AIKIDO_MOE_MBS", "0,1,2,3,4").split(",") if m.strip()]
    moe_cbs = [c.strip() for c in os.environ.get("AIKIDO_MOE_CODEBOOKS", ",".join(c for c in cbs if c in ("0", "1", "2"))).split(",") if c.strip()]
    # AIKIDO_MOE_BITS="3,4": EXL3 K of the experts (3 = GLM-5.3 TR3 experts, byte-exact tile staging; 4 = lane-major repack)
    moe_bits = [b.strip() for b in os.environ.get("AIKIDO_MOE_BITS", "3,4").split(",") if b.strip()]
    moe_sources = ["exl3_hopper_moe.cu", "exl3_moe_orig_builder.cu"]
    # cb 13 = MCG through a 128 KB shared-memory table: decode block families only (0 = 8 rows, 1 = 16 rows); larger
    # families have no shared memory left for the table. AIKIDO_MOE_LUT=0 leaves it out of the build.
    moe_variants = [(mb, cb, kb) for mb in moe_mbs for cb in moe_cbs for kb in moe_bits]
    if os.environ.get("AIKIDO_MOE_LUT", "0") == "1" and "1" in moe_cbs:   # off: dead end at decode sizes (research/12 section 12.3)
        moe_variants += [(mb, "13", kb) for mb in moe_mbs if mb in ("0", "1") for kb in moe_bits]
    for mb, cb, kb in moe_variants:
        path = os.path.join(gen, f"moe_inst_mb{mb}_cb{cb}_k{kb}.cu")
        text = (f"#define AIKIDO_INST_MB {mb}\n#define AIKIDO_INST_CB {cb}\n#define AIKIDO_INST_BITS {kb}\n"
                f"#include \"exl3_hopper_moe_inst.h\"\n")
        if not os.path.exists(path) or open(path).read() != text:
            open(path, "w").write(text)
        moe_sources.append(os.path.relpath(path, here))
    moe_fam = os.path.join(gen, "aikido_moe_families.h")
    moe_fam_text = ("// generated by setup.py\n#pragma once\n#define AIKIDO_MOE_VARIANTS(X) "
                    + " ".join(f"X({mb}, {cb}, {kb})" for mb, cb, kb in moe_variants) + "\n")
    if not os.path.exists(moe_fam) or open(moe_fam).read() != moe_fam_text:
        open(moe_fam, "w").write(moe_fam_text)
    moe_ext = cpp_extension.CUDAExtension(
        "aikido_exl3_moe_kernels",
        moe_sources,
        include_dirs=[here, os.path.join(here, "third_party", "marlin"), gen],
        extra_compile_args={"cxx": ["-O3"], "nvcc": nvcc},
    )
    ext_modules = [moe_ext] if moe_mode == "only" else ext_modules + [moe_ext]
# ---- MoE front (end)

setup(
    name="aikido_exl3_kernels",
    version="0.1.0",
    ext_modules=ext_modules,
    cmdclass={"build_ext": cpp_extension.BuildExtension},
)
